# Generated by Django 4.2.13 on 2024-07-19 14:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovacionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_iniciativa', models.CharField(max_length=255)),
                ('objetivos_clave', models.CharField(max_length=255)),
                ('fase_innovacion', multiselectfield.db.fields.MultiSelectField(choices=[('1. Identificación de la necesidad o problema', '1. Identificación de la necesidad o problema'), ('2. Generación de ideas', '2. Generación de ideas'), ('3. Selección de ideas', '3. Selección de ideas'), ('4. Desarrollo del prototipo', '4. Desarrollo del prototipo'), ('5. Pruebas y validación', '5. Pruebas y validación'), ('6. Implementación', '6. Implementación')], max_length=159)),
                ('proposito_iniciativa', multiselectfield.db.fields.MultiSelectField(choices=[('Análisis de tendencias', 'Análisis de tendencias'), ('Comprender necesidades de usuarios', 'Comprender necesidades de usuarios'), ('Generación de ideas', 'Generación de ideas'), ('Identificación de oportunidades de mercado', 'Identificación de oportunidades de mercado'), ('Evaluación de competencia', 'Evaluación de competencia'), ('Innovación tecnológica', 'Innovación tecnológica'), ('Conocimiento del usuario', 'Conocimiento del usuario'), ('Segmentación de nichos de mercado', 'Segmentación de nichos de mercado'), ('Innovación disruptiva', 'Innovación disruptiva')], max_length=250)),
                ('urgencia', models.CharField(choices=[('1', '1 - Muy bajo: No hay presión para implementar la solución rápidamente.'), ('2', '2 - Bajo: La implementación puede esperar un poco más, no es una prioridad inmediata.'), ('3', '3 - Moderado: Existe cierta presión para implementar la solución en un plazo razonable.'), ('4', '4 - Alto: Se necesita una implementación relativamente rápida para abordar el problema.'), ('5', '5 - Muy Alto: La situación es urgente y se necesita una solución inmediata.')], max_length=1)),
                ('complejidad', models.CharField(choices=[('1', '1 - Muy bajo: El problema es simple y bien definido.'), ('2', '2 - Bajo: La complejidad en mínima y se entiende claramente.'), ('3', '3 - Moderado: Hay algunas áreas de complejidad, pero en su mayoría está bien definido.'), ('4', '4 - Alto: El problema es complejo y requiere una comprensión detallada para abordarlo.'), ('5', '5 - Muy Alto: La complejidad es extremadamente alta y el problema es difícil de definir.')], max_length=1)),
                ('incertidumbre', models.CharField(choices=[('1', '1 - Muy bajo: Hay una comprensión completa del problema y las soluciones posibles.'), ('2', '2 - Bajo: Se tiene una idea general, pero hay cierta incertidumbre sobre las soluciones.'), ('3', '3 - Moderado: Existen algunas áreas de incertidumbre, pero en su mayoría se tiene una comprensión razonable del problema.'), ('4', '4 - Alto: Hay una cantidad significativa de incertidumbre sobre el problema y las soluciones.'), ('5', '5 - Muy Alto: La incertidumbre es extremadamente alta y no se comprende completamente el problema o las posibles soluciones.')], max_length=1)),
                ('colaboracion', models.CharField(choices=[('1', '1 - Muy bajo: No se requiere colaboración significativa, el proyecto es manejable por un solo equipo.'), ('2', '2 - Bajo: Se necesitará alguna colaboración, pero los equipos pueden trabajar de forma independiente en su mayoría.'), ('3', '3 - Moderado: La colaboración entre equipos es importante, pero no es crítica para el éxito.'), ('4', '4 - Alto: La colaboración es esencial y varios equipos deben trabajar estrechamente juntos.'), ('5', '5 - Muy Alto: La colaboración entre múltiples equipos es absolutamente crucial para el éxito del proyecto.')], max_length=1)),
                ('recursos', models.CharField(choices=[('1', '1 - Muy bajo: Recursos muy limitados, es difícil obtener lo que se necesita.'), ('2', '2 - Bajo: Los recursos son escasos, pero se pueden obtener con esfuerzo.'), ('3', '3 - Moderado: Los recursos están disponibles, pero con algunas restricciones.'), ('4', '4 - Alto: Hay suficientes recursos disponibles para llevar a cabo el proyecto.'), ('5', '5 - Muy Alto: Recursos abundantes y fácilmente accesibles para apoyar el proyecto.')], max_length=1)),
                ('flexibilidad', models.CharField(choices=[('1', '1 - Muy bajo: Se espera que el alcance del proyecto permanezca relativamente constante.'), ('2', '2 - Bajo: Puede haber algunos cambios menores, pero el alcance general se mantendrá.'), ('3', '3 - Moderado: Se esperan algunos cambios significativos, pero el alcance general permanecerá similar.'), ('4', '4 - Alto: Se anticipan cambios importantes en el alcance del proyecto.'), ('5', '5 - Muy Alto: La flexibilidad es fundamental, se esperan cambios drásticos en el alcance del proyecto.')], max_length=1)),
                ('velocidad', models.CharField(choices=[('1', '1 - Muy bajo: La velocidad de implementación no es una prioridad.'), ('2', '2 - Bajo: Se prefiere una implementación más rápida, pero no es crítica.'), ('3', '3 - Moderado: La implementación oportuna es importante para el éxito del proyecto.'), ('4', '4 - Alto: Se necesita una implementación rápida para obtener beneficios rápidos.'), ('5', '5 - Muy Alto: La velocidad de implementación es esencial y se espera que sea lo más rápido posible.')], max_length=1)),
                ('riesgo', models.CharField(choices=[('1', '1 - Muy bajo: Riesgo mínimo, el fracaso no tendría un gran impacto.'), ('2', '2 - Bajo: Algunos riesgos, pero manejables y el impacto de un fracaso sería moderado.'), ('3', '3 - Moderado: Riesgos significativos, un fracaso tendría un impacto considerable.'), ('4', '4 - Alto: Riesgo alto, un fracaso tendría un impacto importante en el proyecto.'), ('5', '5 - Muy Alto: Riesgo extremadamente alto, un fracaso tendría consecuencias catastróficas.')], max_length=1)),
                ('usuario', models.CharField(choices=[('1', '1 - Muy bajo: No se tiene información alguna sobre los usuarios.'), ('2', '2 - Bajo: Hay una comprensión superficial de los usuarios, pero se requiere más investigación.'), ('3', '3 - Moderado: Se dispone de alguna información sobre los usuarios, pero se necesitan más detalles para comprender completamente sus necesidades.'), ('4', '4 - Alto: Existe una comprensión significativa de los usuarios y sus necesidades, pero aún se pueden requerir ajustes adicionales.'), ('5', '5 - Muy Alto: Se posee un conocimiento profundo y detallado de los usuarios, incluyendo sus necesidades, deseos y comportamientos.')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosInnovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default=' ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
