# Generated by Django 4.2.13 on 2024-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessity_artifact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovacionformulario',
            name='descripcion_iniciativa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='innovacionformulario',
            name='objetivos_clave',
            field=models.TextField(),
        ),
    ]
