# Generated by Django 4.1 on 2024-07-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_dimension', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ponderation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Feasibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feasibility', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ponderation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FeasibilityCalifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UseCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
            ],
        ),
    ]
